CREATE TABLE TMP_BE_STMT_DETAIL_AGG NOLOGGING PARALLEL 4 AS
WITH stmt_detail_ranked AS (
    SELECT
        CARD_ID,
        TRUNC(TRX_DATE, 'MM') AS TRX_MONTH,
        FEE_AMOUNT,
        REMAINING_INSTALLMENT_AMOUNT,
        REMAINING_INSTALLMENT_COUNT,
        TOTAL_INSTALLMENT_AMOUNT,
        TOTAL_INSTALLMENT_COUNT,
        ROW_NUMBER() OVER (
            PARTITION BY CARD_ID, TRUNC(TRX_DATE, 'MM')
            ORDER BY TRX_DATE DESC
        ) AS rn
    FROM   CORE.CARD_STATEMENT_DETAIL
    WHERE  TRX_DATE >= :START_DATE
)
SELECT
    CARD_ID,
    TRX_MONTH,
    SUM(FEE_AMOUNT)                                                    AS FEE_AMOUNT,
    MAX(CASE WHEN rn = 1 THEN REMAINING_INSTALLMENT_AMOUNT END)       AS REMAINING_INSTALLMENT_AMOUNT,
    MAX(CASE WHEN rn = 1 THEN REMAINING_INSTALLMENT_COUNT END)        AS REMAINING_INSTALLMENT_COUNT,
    SUM(TOTAL_INSTALLMENT_AMOUNT)                                      AS TOTAL_INSTALLMENT_AMOUNT,
    SUM(TOTAL_INSTALLMENT_COUNT)                                       AS TOTAL_INSTALLMENT_COUNT
FROM   stmt_detail_ranked
GROUP BY CARD_ID, TRX_MONTH
