CREATE TABLE TMP_BE_STMT_MONTHLY NOLOGGING PARALLEL 4 AS
SELECT
    bc.CARD_ID,
    TRUNC(bc.MONTH_END, 'MM') AS TRX_MONTH,
    sa.PRE_STMT_PYMNT_MIN_AMT,
    sa.STMT_PYMNT_AMT,
    sa.STMT_PYMNT_MIN_AMT,
    sa.STMT_REVOLVING_AMT,
    sd.FEE_AMOUNT,
    sd.REMAINING_INSTALLMENT_AMOUNT,
    sd.REMAINING_INSTALLMENT_COUNT,
    sd.TOTAL_INSTALLMENT_AMOUNT,
    sd.TOTAL_INSTALLMENT_COUNT
FROM   TMP_BE_CARD_SNAPSHOT bc
LEFT JOIN TMP_BE_STMT_AGG sa
       ON sa.CARD_ID   = bc.CARD_ID
      AND sa.MONTH_END = bc.MONTH_END
LEFT JOIN TMP_BE_STMT_DETAIL_AGG sd
       ON sd.CARD_ID   = bc.CARD_ID
      AND sd.TRX_MONTH = TRUNC(bc.MONTH_END, 'MM')
