CREATE TABLE TMP_BE_PROFIT_MONTHLY NOLOGGING PARALLEL 4 AS
SELECT
    CARD_ID,
    AS_OF_MONTH,
    TOTAL_PROFIT,
    MERCHANT_COMMISSION,
    INSURANCE_COMMISSION,
    FEE AS PROFIT_FEE,
    LOAN_NET_INTEREST_INCOME,
    IMPAIRMENT_LOSSES,
    CASH_ADVANCE_COMMISSION
FROM   CORE.PROFIT_CARD_CC_MONTHLY
WHERE  AS_OF_MONTH >= :START_YYYYMM
