CREATE TABLE TMP_BE_TLMK_MONTHLY NOLOGGING PARALLEL 4 AS
SELECT
    bc.CARD_ID,
    TRUNC(bc.MONTH_END, 'MM') AS ISSUE_MONTH,
    COUNT(iss.ISSUE_NUMBER)   AS NUMBER_OF_ISSUES
FROM   TMP_BE_CARD_SNAPSHOT bc
LEFT JOIN CORE.ISSUE iss
       ON iss.CARD_ID = bc.CARD_ID
      AND TRUNC(iss.ISSUE_CREATEDATE, 'MM') = TRUNC(bc.MONTH_END, 'MM')
GROUP BY
    bc.CARD_ID,
    TRUNC(bc.MONTH_END, 'MM')
