CREATE TABLE TMP_BE_TRX_MONTHLY NOLOGGING PARALLEL 4 AS
SELECT
    t.CARD_ID,
    TRUNC(t.VALUE_DT, 'MM')  AS TRX_MONTH,
    COUNT(*)                  AS TRX_CNT_MTH,
    SUM(t.TRX_AMT)           AS TRX_AMT_MTH,
    CASE WHEN COUNT(*) > 0
         THEN SUM(t.TRX_AMT) / COUNT(*)
         ELSE 0
    END                       AS AVG_TICKET_MTH,
    MEDIAN(t.TRX_AMT)        AS MEDIAN_TICKET_MTH
FROM   DWH.CARD_TRX_ISSUING t
WHERE  t.VALUE_DT >= :START_DATE
GROUP BY t.CARD_ID, TRUNC(t.VALUE_DT, 'MM')
