CREATE TABLE TMP_BE_MCC_FREQ_RANKED NOLOGGING PARALLEL 4 AS
SELECT
    t.CARD_ID,
    TRUNC(t.VALUE_DT, 'MM')  AS TRX_MONTH,
    t.MERCHANT_CATEG_CODE,
    ROW_NUMBER() OVER (
        PARTITION BY t.CARD_ID, TRUNC(t.VALUE_DT, 'MM')
        ORDER BY COUNT(*) DESC
    ) AS rn
FROM   DWH.CARD_TRX_ISSUING t
WHERE  t.VALUE_DT >= :START_DATE
GROUP BY t.CARD_ID, TRUNC(t.VALUE_DT, 'MM'), t.MERCHANT_CATEG_CODE
