SELECT
    cs.CARD_ID,
    cs.MONTH_END,
    cs.BRCH_CODE,
    cs.STATUS,
    cs.CARD_LIMIT,
    cs.TOTAL_EXPOSURE_AMT,
    cs.OVERDUE_AMT_RON,
    cs.FUTURE_INST_AMT,
    cs.BONUS_AMT,
    cs.DPD,
    cs.TIMES_IN_5_DPD,
    cs.TIMES_IN_30_DPD,
    cs.TIMES_IN_60_DPD,
    cs.TIMES_IN_90_DPD,
    cs.TIMES_IN_90_PLUS_DPD,
    cs.LAST_EXPOSURE_DATE,
    cs.SENT_TO_LEGAL,
    cs.DOD,
    cs.POOL_RT,
    cs.ILOE,
    cs.DOUBTFUL_INT_AMT,
    cs.DOUBTFUL_INT_PEN_AMT,
    cs.DOUBTFUL_PRIN_AMT,
    cs.DOUBTFUL_PRIN_PEN_AMT,
    cs.FUTURE_INST_INT,
    cs.FUTURE_INST_INT_OVRD_DBT,
    cs.FUTURE_INST_OVRD_DBT,
    cs.MARKETING_INFO,
    cs.NO_OF_SUB_CARD,
    cs.OSTND_INT_AMT,
    cs.OSTND_PRIN_AMT,
    cs.OVRD_INT_AMT,
    cs.OVRD_INT_PEN_AMT,
    cs.OVRD_PRIN_AMT,
    cs.OVRD_PRIN_PEN_AMT,
    cs.TOTAL_INT_AMT,
    cs.TOTAL_PENALTY_AMT,
    cs.CARD_CANCELLATION_DATE,
    cu.CNTRY,
    cu.CITY,
    cu.EDUCATION,
    cu.RISK_LEVEL,
    cu.ADVERTISING,
    cu.BIRTH_DT,
    cu.OPEN_DT,
    sm.PRE_STMT_PYMNT_MIN_AMT,
    sm.STMT_PYMNT_AMT,
    sm.STMT_PYMNT_MIN_AMT,
    sm.STMT_REVOLVING_AMT,
    sm.FEE_AMOUNT,
    sm.REMAINING_INSTALLMENT_AMOUNT,
    sm.REMAINING_INSTALLMENT_COUNT,
    sm.TOTAL_INSTALLMENT_AMOUNT,
    sm.TOTAL_INSTALLMENT_COUNT,
    pm.TOTAL_PROFIT,
    pm.MERCHANT_COMMISSION,
    pm.INSURANCE_COMMISSION,
    pm.PROFIT_FEE AS FEE,
    pm.LOAN_NET_INTEREST_INCOME,
    pm.IMPAIRMENT_LOSSES,
    pm.CASH_ADVANCE_COMMISSION,
    tm.TRX_CNT_MTH,
    tm.AVG_TICKET_MTH,
    tm.MEDIAN_TICKET_MTH,
    tm.TRX_AMT_MTH,
    tlm.NUMBER_OF_ISSUES,
    mf.MERCHANT_CATEG_CODE       AS MCC_MOST_FREQUENT_MTH,
    ms.MERCHANT_CATEG_CODE       AS MCC_MOST_SPENT_MTH
FROM      TMP_BE_CARD_SNAPSHOT cs
LEFT JOIN CORE.CUSTOMER cu
       ON cu.CUST_ID = cs.CUST_ID
LEFT JOIN TMP_BE_STMT_MONTHLY sm
       ON sm.CARD_ID   = cs.CARD_ID
      AND sm.TRX_MONTH = TRUNC(cs.MONTH_END, 'MM')
LEFT JOIN TMP_BE_PROFIT_MONTHLY pm
       ON pm.CARD_ID     = cs.CARD_ID
      AND pm.AS_OF_MONTH = EXTRACT(YEAR FROM cs.MONTH_END) * 100
                         + EXTRACT(MONTH FROM cs.MONTH_END)
LEFT JOIN TMP_BE_TRX_MONTHLY tm
       ON tm.CARD_ID   = cs.CARD_ID
      AND tm.TRX_MONTH = TRUNC(cs.MONTH_END, 'MM')
LEFT JOIN TMP_BE_TLMK_MONTHLY tlm
       ON tlm.CARD_ID     = cs.CARD_ID
      AND tlm.ISSUE_MONTH = TRUNC(cs.MONTH_END, 'MM')
LEFT JOIN TMP_BE_MCC_FREQ_RANKED mf
       ON mf.CARD_ID   = cs.CARD_ID
      AND mf.TRX_MONTH = TRUNC(cs.MONTH_END, 'MM')
      AND mf.rn        = 1
LEFT JOIN TMP_BE_MCC_SPENT_RANKED ms
       ON ms.CARD_ID   = cs.CARD_ID
      AND ms.TRX_MONTH = TRUNC(cs.MONTH_END, 'MM')
      AND ms.rn        = 1
